class Main {
	main():IO {{
		$
		new &IO.out_string("Hellosvgajsvgashvgasjgshfawegiwyvvefwvfyigqwinnwvuwfeygbebebfywefbfgeqwnhqeqdnhqeqhnwirygweyirbfgbdfg\
wyrgwuebvgwevgrbwybgregryqgrgqwcnrqwnewrdfwqbvebrwierwfebrwiduehfbrgdubegrufw4rbfkbdfbgdbfgaglberuigfuiglasigsabdfbvdvksvfkabsfbsvkbskvh\
bslkbfsbdfbasfbasdklfbsidbvlksvbksbfvksabvkbaskjlvbaskfjvbskljfbvkasbvkjsbfvksbfvskdjvbsjkvbaskjbvskvjbaskjvbdkvaskasdfansgdsnvasuifsbv\
fbskdfbasdjfklabssdbclbdcvbsajkbvkasbvksabkvjbaskjdvhbbrbsfvbshbasbdfagsfbsavbsvdbshvbsfiusfbsbisaufvbjsbsibsvkjbsduvsgbvkjsiufbvskbv\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs\
sfybsbvahvbaisufbskjdfsoufcsnkjvsufhscsnsufdosnvushushuvsdvbsrufsbsvkjafuisfdbskfsufhsubsnkvbasfuasfnsfohausfnasfhufhasuodfhygefasdkfbs");
		^
		}};

};
